name: primary_school_math_calculation_generator
description: A math problem generator for primary school students

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  syncfusion_flutter_pdf: ^28.2.6
  file_picker: ^9.0.0
  intl: ^0.20.2
  uuid: ^4.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  material_color_utilities: ^0.11.1

flutter:
  uses-material-design: true
